app/urls.py
from .views import (HomeView, RegisterView, success_form, SendDocumentView, \
                    List_Client, UpdateClientView, UserProfileView, SearchClientView,
                    ActiveStatusClientView, BlockStatusClientView, DoneStatusClientView)
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/register', RegisterView.as_view(), name='register'),
    path('user/<int:pk>/', UserProfileView.as_view(), name='user_profile'),
    path('document/', SendDocumentView.as_view(), name='send_document'),
    path('success_form/', success_form, name='success_form'),
    path('list-client/', List_Client.as_view(), name='list_client'),
    path('client/<int:pk>/', UpdateClientView.as_view(), name='detail_client'),
    path('search_client/', SearchClientView.as_view(), name='search_client'),
    path('active_status/', ActiveStatusClientView.as_view(), name='active_status_client'),
    path('block_status/', BlockStatusClientView.as_view(), name='block_status_client'),
    path('done_status/', DoneStatusClientView.as_view(), name='done_status_client')

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zagran_pasport/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User


class Client(models.Model):
    GENDER = (
        ('male', 'мужчина'),
        ('female', 'женшина')
    )
    STATUS = (
        ('Готово', 'done'),
        ('Астывна', 'active'),
        ('Отменён', 'block'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    second_name = models.CharField(max_length=100)
    patronymic = models.CharField(max_length=100)
    age = models.IntegerField(default=18)
    gender = models.CharField(choices=GENDER, max_length=100)
    was_born = models.DateField(default='2004-01-01')
    passport_left = models.FileField(upload_to='document')
    passport_right = models.FileField(upload_to='document')
    recipient_amonatbonck = models.FileField(upload_to='amonatbonck')
    phone = models.CharField(max_length=200)
    is_active = models.BooleanField(default=True)
    status_document = models.CharField(max_length=100, choices=STATUS, default='Астывна')
    message = models.TextField(blank=True, default='Test Message')
    created_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    update_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    email = models.EmailField()
    editable = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.first_name} {self.second_name}"

app/forms.py
from .models import Client
from django import forms

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterUser(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('first_name', 'second_name',  'patronymic', 'age', 'gender', 'was_born', 'email',
                  'phone',  'passport_left', 'passport_right', 'recipient_amonatbonck')


class AdminClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('first_name', 'second_name',  'patronymic', 'age', 'gender', 'was_born', 'email', 'status_document',
                  'passport_left', 'passport_right', 'recipient_amonatbonck', 'phone', 'editable', 'is_active')

app/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import ClientForm, RegisterUser, AdminClientForm
from .models import Client
from django.views import generic


class HomeView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'app/main.html'


class RegisterView(generic.CreateView):
    form_class = RegisterUser
    template_name = 'registration/register.html'

    def get_success_url(self):
        return reverse('login')


# def register(request):
#     msg = None
#     form = RegisterUser
#     if request.method == 'POST':
#         form = RegisterUser(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('login')
#     return render(request, 'registration/register.html')


class List_Client(generic.ListView):
    queryset = Client.objects.all()
    template_name = 'app/list_client.html'

    def get_success_url(self):
        return reverse('success_form')


class UpdateClientView(generic.UpdateView):
    form_class = AdminClientForm
    queryset = Client.objects.all()
    context_object_name = 'client'
    template_name = 'app/update_client_document.html'

    def get_success_url(self):
        return reverse('list_client')


class UserProfileView(LoginRequiredMixin, generic.DetailView):
    queryset = Client.objects.all()
    context_object_name = 'client'
    template_name = 'app/userprofile.html'


class SendDocumentView(LoginRequiredMixin, generic.CreateView):
    form_class = ClientForm
    template_name = 'app/send_document.html'

    def form_valid(self, form):
        document = form.save(commit=False)
        document.user = self.request.user
        document.created_at = datetime.now()
        document.update_at = datetime.now()
        document.editable = False

        # document.save()
        return super(SendDocumentView, self).form_valid(form)

    def get_success_url(self):
        return reverse('success_form')


# def send_document(request):
#     if request.method == 'POST':
#         form = ClientForm(request.POST, request.FILES)
#         if form.is_valid():
#             data = form.cleaned_data
#             Client.objects.create(
#                 user=request.user,
#                 name=data['name'],
#                 surname=data['surname'],
#                 phone=data['phone'],
#                 passport=data['passport'],
#                 receipt_amonatbonk=data['receipt_amonatbonk']
#             )
#             return redirect('success_form')
#
#     else:
#         form = ClientForm()
#     return render(request, 'app/send_document.html', {'form': form})


# def user_profile(request, pk):
#     profile = Client.objects.get(user_id=pk)
#     return render(request, 'app/user_profile.html', {'profile': profile})


class ActiveStatusClientView(LoginRequiredMixin, generic.ListView):
    template_name = 'app/search_client.html'

    def get_queryset(self):
        client_list = None
        if self.request.user.is_superuser:
            print('q------->>')
            client_list = Client.objects.filter(status_document='Астывна')
            print('client_list', client_list)
        return client_list


class BlockStatusClientView(LoginRequiredMixin, generic.ListView):
    template_name = 'app/search_client.html'

    def get_queryset(self):
        client_list = None
        if self.request.user.is_superuser:
            print('q------->>')
            client_list = Client.objects.filter(status_document='Отменён')
            print('client_list', client_list)
        return client_list


class DoneStatusClientView(LoginRequiredMixin, generic.ListView):
    template_name = 'app/search_client.html'

    def get_queryset(self):
        client_list = None
        if self.request.user.is_superuser:
            print('q------->>')
            client_list = Client.objects.filter(status_document='Готово')
            print('client_list', client_list)
        return client_list


class SearchClientView(LoginRequiredMixin, generic.ListView):
    template_name = 'app/search_client.html'

    def get_queryset(self):
        client_list = None
        if self.request.user.is_superuser:
            query = self.request.GET.get('q')
            print('q------->>', query)
            client_list = Client.objects.filter(Q(phone__icontains=query)
                                                | Q(first_name__icontains=query)
                                                | Q(second_name__icontains=query))
            print('client_list', client_list)
        return client_list


def success_form(request):
    return render(request, 'app/success_form.html')

app/templates/app/list_client.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<hr/>
<div class="musor">
<div class="content-button">
  <a href="{% url 'active_status_client' %}" class="buton one " type="submit" >Активные</a>
  <a href="{% url 'block_status_client' %}" class="buton two" type="submit">Заблокированные</a>
  <a href="{% url 'done_status_client' %}" class="buton  three" type="submit">Готовые</a>

</div>
</div>
  <div class="container-fluid my-3">
    <form class="d-flex" role="search" method="get" action="{% url 'search_client' %}">
      <input name="q" class="form-control me-2" type="text" placeholder="Search" aria-label="Search">
      <button class="search" type="submit">Поиск</button>
    </form>
  </div>
<table class="table table-dark table-hover table-bordered border-primary">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Имя </th>
      <th scope="col">Фамилия</th>
      <th scope="col">Отчество</th>
      <th scope="col">Статус документа</th>
      <th scope="col">Дата рождения</th>
      <th scope="col">Возраст</th>
      <th scope="col">Пол</th>
      <th scope="col">Номер телефона</th>
      <th scope="col">Дата создания</th>
        <th scope="col">Изменить</th>
    </tr>
  </thead>
{% for client in object_list %}

  <tbody>
    <tr>
      <th scope="row">{{ client.pk }}</th>
       <td>{{ client.first_name }}</td>
      <td>{{ client.second_name }}</td>
      <td>{{ client.patronymic }}</td>
      {% if  client.status_document == 'Готово' %}
          <td style="color: #34C924;">{{ client.status_document }} </td>
      {% elif client.status_document == 'Астывна' %}
          <td style="color: red;">{{ client.status_document }} </td>
      {% else %}
        <td style="color: #FFCF48;">{{ client.status_document }} </td>
      {% endif %}
      <td>{{ client.was_born }}</td>
      <td>{{ client.age }}</td>
       <td>{{ client.gender }}</td>
      <td>{{ client.phone }}</td>
      <td>{{ client.created_at }}</td>

        <td><a href="{% url 'detail_client' client.pk %}">More</a></td>
    </tr>
  </tbody>


{% endfor %}
</table>
<style>
  body {
    background: #black;
  }
  .musor {
    padding-top: 50px;
    background: #000;
    width: 100%;
    height: 150px;
    border-radius: 20px;
  }
  .container-fluid{


    padding-left: 50%;
    padding-right: 100px;
    padding-top: 20px;
    padding-bottom: 20px;
 }
 .buton {

  font-size: 20px;
  border-radius: 10px;
  padding-top: 12px;
  text-align: center;
  background-color: #007FFF;
  width: 450px;
  height: 50px;

  color: white;
  text-decoration: none;

}

 .content-button {

  display: flex;
  justify-content: space-around;
 }
 .one {
  background: red;
 }
 .two {
  background: #FFCF48;

 }
 .three {
  background: #34C924;
 }
 .search {
  color: #fff;
  border: none;
  background: blue;
  border-radius: 10px;
  width: 200px;
  height: 50px;
 }
</style>


{% endblock %}

app/templates/app/main.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/7ae93f3ba1.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
    <link rel="icon" href="{% static '/illustration/web_logo.png'  %}" type="image/x-con">
    <title>Zagran.tj</title>
<body>
    <header>
        <img src="{% static 'logo/Zagran.tj.png' %} " alt="logo">

        <nav>
            <ul class="nav_links">
                {% if user.is_superuser %}
                 <a class="nav-link" href="{% url 'list_client' %}">Админ панел</a>
                {% endif %}
                 {% if user.is_authenticated %}
                <a class="nav-link btn-primary" href="{% url 'logout' %}">Logout</a>
                <a class="nav-link" href="{% url 'user_profile' user.pk %}" >{{ user }}</a>
               {% else %}
                <a class="nav-link " href="{% url 'login' %}">Login</a>
                <a class="nav-link" href="{% url 'register' %}">Register</a>
             {% endif %}

            </ul>
        </nav>

    </header>
    <div class="offer">
        <div class="text">Онлайн подача документов <br>для оформления Загранпаспорта</div>
        <img src="{% static 'illustration/plane.png' %}" alt="plane" class="plane" style="width: 300px; padding-bottom: 20px; padding-top: 20px;">
    </div>
        <p class="oglavlenie">Виды оформления</p>
        <div class="cards">
            <a  href="{% url 'send_document' %}" >
        <div class="card-conteiner1">

            <img src="{% static 'illustration/card1.png' %}" alt="{% url 'send_document' %}" class="icons">
            <p  class="card_main_text">Для <br> Совершеннолетних</p>
            <p  class="card_text">Для граждан достигли <br> или старше 16 лет<br> возраста</p>

        </div>
         </a>
        <div class="card-conteiner2">
            <img  src="{% static 'illustration/card2.png' %} " alt="" class="icons">
            <p class="card_main_text">Для <br> Повторной подачи</p>
            <p class="card_text">Для граждан которые <br> повторно подают или утеряли <br> предыдущий заграничный паспорт</p>
        </div>

        <div class="card-conteiner3">
            <img src="{% static '/illustration/card3.png' %}" alt="" class="icons">
            <p class="card_main_text">Для <br> Несовершеннолетних</p>
            <p class="card_text">Для граждан не достигших <br> совершеннолетнего <br> возраста и младенцев </p>
        </div>
    </div>
    <p class="oglavlenie">Полезная информация</p>
    <div class="q_cards">
        <div class="q_card_conteiner">
            <img src="{% static 'illustration/undraw_upload_re_pasx.png' %}" alt="" style="width: 240px;">
            <a href="info/PDF Document.pdf" download=" " class="q_text">Перечень документов</a>
        </div>

        <div class="q_card_conteiner">
            <img src="illustration/undraw_connected_world_wuay.png" alt="" style="width: 228px;">
            <a  href="info/PDF Document.pdf" class="q_text">
                Каким гражданам запрещена выдача Загранпаспорта?
            </a>
        </div>

        <div class="q_card_conteiner" >
            <img src="illustration/undraw_map_dark_re_36sy.png" alt="" style="width: 190px;">
            <a  href="info/PDF Document.pdf" class="q_text">
                Отеделы паспортного стола
            </a>
        </div>

    </div>



    <footer class="footer">
        <div class="conteiner">
            <div class="row">
                <div class="footer-col">
                    <h4>Компания</h4>
                    <ul>
                        <li><a href="">О нас</a></li>
                        <li><a href="">Политика конфиденциальности</a></li>
                        <li><a href="">Личный кобинет</a></li>
                        <li><a href=""></a></li>
                    </ul>
                    
                </div>
                <div class="footer-col">
                    <h4>Помощь</h4>
                    <ul>
                        <li><a href="">Поддержка</a></li>
                        <li><a href="">Способы оплаты</a></li>
                        <li><a href="">FAQ</a></li>
                        <li><a href=""></a></li>
                    </ul>
                    
                </div>
                <div class="footer-col">
                    <h4>Соц.сети</h4>
                    <div class="social-links"> 
                        <a href=""><i class="fa-brands fa-facebook"></i></a>
                        <a href=""><i class="fa-brands fa-twitter"></i></a>
                        <a href=""><i class="fa-brands fa-instagram"></i></a>
                        <a href=""><i class="fa-brands fa-linkedin"></i></a>
                    </div>
                </div> 
            </div>
        </div>
    </footer>
    <script src="">
    </script>
    <style>
       a {
    text-decoration: none;
         }
    </style>
</body>
</html>

app/templates/app/search_client.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<hr/>
<div class="musor">
<div class="content-button">
  <a href="{% url 'active_status_client' %}" class="buton one " type="submit" >Активные</a>
  <a href="{% url 'block_status_client' %}" class="buton two" type="submit">Заблокированные</a>
  <a href="{% url 'done_status_client' %}" class="buton  three" type="submit">Готовые</a>

</div>
</div>

</div>
  <div class="container-fluid my-3">
    <form class="d-flex" role="search" method="get" action="{% url 'search_client' %}">
      <input name="q" class="form-control me-2" type="text" placeholder="Search" aria-label="Search">
      <button class="search" type="submit">Поиск</button>
    </form>
  </div>
<table class="table table-dark table-hover table-bordered border-primary">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Имя </th>
      <th scope="col">Фамилия</th>
      <th scope="col">Отчество</th>
      <th scope="col">Статус документа</th>
      <th scope="col">Дата рождения</th>
      <th scope="col">Возраст</th>
      <th scope="col">Пол</th>
      <th scope="col">Номер телефона</th>
      <th scope="col">Дата создания</th>
        <th scope="col">Изменить</th>
    </tr>
  </thead>
{% for client in object_list %}

  <tbody>
        <tr>
      <th scope="row">{{ client.pk }}</th>
       <td>{{ client.first_name }}</td>
      <td>{{ client.second_name }}</td>
      <td>{{ client.patronymic }}</td>
      {% if  client.status_document == 'Готово' %}
          <td style="color: #34C924;">{{ client.status_document }} </td>
      {% elif client.status_document == 'Астывна' %}
          <td style="color: red;">{{ client.status_document }} </td>
      {% else %}
        <td style="color: #FFCF48;">{{ client.status_document }} </td>
      {% endif %}
      <td>{{ client.was_born }}</td>
      <td>{{ client.age }}</td>
       <td>{{ client.gender }}</td>
      <td>{{ client.phone }}</td>
      <td>{{ client.created_at }}</td>

        <td><a href="{% url 'detail_client' client.pk %}">More</a></td>
    </tr>
  </tbody>


{% endfor %}
</table>
<style>
  .container-fluid{
    padding-left: 50%;
    padding-right: 100px;
    padding-top: 20px;
    padding-bottom: 20px;
 }
  body {
    background: #black;
  }
  .musor {
    padding-top: 50px;
    background: #000;
    width: 100%;
    height: 150px;
    border-radius: 20px;
  }
  .container-fluid{


    padding-left: 50%;
    padding-right: 100px;
    padding-top: 20px;
    padding-bottom: 20px;
 }
 .buton {

  font-size: 20px;
  border-radius: 10px;
  padding-top: 12px;
  text-align: center;
  background-color: #007FFF;
  width: 450px;
  height: 50px;

  color: white;
  text-decoration: none;

}

 .content-button {

  display: flex;
  justify-content: space-around;
 }
 .one {
  background: red;
 }
 .two {
  background: #FFCF48;

 }
 .three {
  background: #34C924;
 }
 .search {
  color: #fff;
  border: none;
  background: blue;
  border-radius: 10px;
  width: 200px;
  height: 50px;
 }
</style>
{% endblock %}

app/templates/app/send_document.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Home page {% endblock  %}
{% block content %}

{% if user.is_authenticated %}

{% if not  user.client or user.client.editable %}



<div class="container-two">
    <h3 class="h3_reg ">Форма заполнения</h3>
<form method="post" action="" enctype="multipart/form-data" class="white">
   {% csrf_token %}

<div id="div_id_first_name" class="form-group"> <label for="id_first_name" class=" requiredField">
                <span class="asteriskField"></span> </label> <div> <input placeholder="Имя" type="text" name="first_name" maxlength="100" class="textinput textInput form-control" required="" id="id_first_name"> </div> </div> <div id="div_id_second_name" class="form-group"> <label for="id_second_name" class=" requiredField">
                <span class="asteriskField"></span> </label> <div> <input  placeholder="Фамилия" type="text" name="second_name" maxlength="100" class="textinput textInput form-control" required="" id="id_second_name"> </div> </div> <div id="div_id_patronymic" class="form-group"> <label for="id_patronymic" class=" requiredField">
                <span class="asteriskField"></span> </label> <div> <input  placeholder="Отчество" type="text" name="patronymic" maxlength="100" class="textinput textInput form-control" required="" id="id_patronymic"> </div> </div> <div id="div_id_age" class="form-group"> <label for="id_age" class=" requiredField">
                <span class="asteriskField"></span> </label> <div> <input placeholder="Возраст" type="number" name="age"  class="numberinput form-control" required="" id="id_age"> </div> </div> <div id="div_id_gender" class="form-group"> <label for="id_gender" class=" requiredField">
                <span class="asteriskField"></span> </label> <div> <select  name="gender" class="select form-control" required="" id="id_gender"> <option value="" selected="">Пол</option> <option value="male">мужчина</option> <option value="female">женшина</option>

</select> </div> </div> <div id="div_id_was_born" class="form-group"> <label for="id_was_born" class=" requiredField">
                <span class="asteriskField"></span> </label> <div> <input placeholder="Дата рождения" type="text" name="was_born"  class="dateinput form-control" required="" id="id_was_born"> </div> </div> <div id="div_id_email" class="form-group"> <label for="id_email" class=" requiredField">
                <span class="asteriskField"></span> </label> <div> <input  placeholder="Email" type="email" name="email" maxlength="254" class="emailinput form-control" required="" id="id_email"> 
                <div id="div_id_phone" class="form-group"> <label for="id_phone" class=" requiredField">
                <span class="asteriskField"></span> </label> <div> <input placeholder="Телефон" type="text" name="phone" maxlength="200" class="textinput textInput form-control" required="" id="id_phone"> </div> </div></div> </div>  <div id="div_id_passport_left" class="form-group"> <label for="id_passport_left" class=" requiredField">
                Левая сторона паспорта<span class="asteriskField"></span> </label> <div> <input type="file" name="passport_left" class="clearablefileinput form-control-file" required="" id="id_passport_left"> </div> </div> <div id="div_id_passport_right" class="form-group"> <label for="id_passport_right" class=" requiredField">
                Правоя сторона паспорта<span class="asteriskField"></span> </label> <div> <input type="file" name="passport_right" class="clearablefileinput form-control-file" required="" id="id_passport_right"> </div> </div> <div id="div_id_recipient_amonatbonck" class="form-group"> <label for="id_recipient_amonatbonck" class=" requiredField">
                Чек банка<span class="asteriskField">*</span> </label> <div> <input type="file" name="recipient_amonatbonck" class="clearablefileinput form-control-file" required="" id="id_recipient_amonatbonck"> </div> </div> 
                </div>

     <button type="submit" class="btn btn-primary">Добавить</button>
</form>
{% else %}
<h2 class="h3_reg">Вы уже заполнили анкету проверяте личный кабинет</h2>

{% endif %}
{% endif %}
</div>
<style>
.h3_reg {
    font-size: 30px;
}
 .form-control {
    width: 300px;
    height: 40px;
    margin: 0 auto;


}

.form-group {
    text-align: center;
}

.container-two {
    
    width: 400px;
    background-color: #fff;
    height: 850px;
    margin: 0 auto;
    margin-top: 0px;
    border-radius: 15px;
}
.btn-primary {
    position: relative;
    width: 300px;
    bottom: 75px;
    height: 40px;
    align-items: center;
    font-size: 20px;
    padding-top:  5px;

}

</style>
{% endblock  %}

app/templates/app/success_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Home page {% endblock  %}
{% block content %}
    <h3 class="my-4">Ваша заявка принята Для проверки статус документа зайдите в личный кабинет</h3>




{% endblock  %}

app/templates/app/update_client_document.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="post" action="">
    {% csrf_token %}
    <p>
    <label class="ramochka" for="id_first_name">Имя:</label>
    <input  class="form-in" type="text" name="first_name" value="Sino" maxlength="100" required="" id="id_first_name">
  </p>


  <p>
    <label  class="ramochka"  for="id_second_name">Фамилия:</label>
    <input class="form-in" type="text" name="second_name" value="Ikromov" maxlength="100" required="" id="id_second_name">
  </p>


  <p>
    <label class="ramochka" for="id_patronymic">Отчество:</label>
    <input class="form-in" type="text" name="patronymic" value="Abduali" maxlength="100" required="" id="id_patronymic">
  </p>


  <p>
    <label  class="ramochka" for="id_age">Возраст:</label>
    <input type="number" name="age" value="18" required="" id="id_age">
  </p>


  <p>
    <label class="ramochka"  for="id_gender">Пол:</label>
    <select name="gender" required="" id="id_gender">
  <option value="">---------</option>

  <option value="male" selected="">мужчина</option>

  <option value="female">женшина</option>

</select>


  </p>


  <p>
    <label class="ramochka"  for="id_was_born">Дата рождения:</label>
    <input  class="form-in" type="text" name="was_born" value="01.01.2004" required="" id="id_was_born">
  </p>


  <p>
    <label class="ramochka" for="id_email">Email:</label>
    <input  class="form-in" type="email" name="email" value="sinoikrmov0@gmail.com" maxlength="254" required="" id="id_email">
  </p>
  <p>
    <label class="ramochka" for="id_status_document">Статус документа:</label>
    <select name="status_document" id="id_status_document">
  <option value="Готово" selected="">done</option>
  <option value="Астывна">active</option>
  <option value="Отменён">block</option>
</select>

  </p>

  <p>
    <label class="ramochka ll" for="id_passport_left">Левая сторона паспорта:</label>
    На данный момент: <a href="/photo/document/223211528_LYCaHcb.jpg">document/223211528_LYCaHcb.jpg</a><br>
Изменить:
<input type="file" name="passport_left" id="id_passport_left">

  </p>

  <p>
    <label class="ramochka ll" for="id_passport_right">Правоя сторона паспорта:</label>
    На данный момент: <a href="/photo/document/mysqlclient-1.4.6-cp38-cp38-win_amd64.whl">document/mysqlclient-1.4.6-cp38-cp38-win_amd64.whl</a><br>
Изменить:
<input class="form-in"  type="file" name="passport_right" id="id_passport_right">

  </p>

  <p>
    <label class="ramochka ll" for="id_recipient_amonatbonck">Чек банка:</label>
    На данный момент: <a href="/photo/amonatbonck/223211528_AXL3a9E.jpg">amonatbonck/223211528_AXL3a9E.jpg</a><br>
Изменить:
<input class="form-in" type="file" name="recipient_amonatbonck" id="id_recipient_amonatbonck">

  </p>

  <p>
    <label class="ramochka ll" for="id_phone">Телефон:</label>
    <input  class="form-in" type="text" name="phone" value="919503018" maxlength="200" required="" id="id_phone">


  </p>

  <p>
    <label class="ramochka ll" for="id_editable">Editable:</label>
    <input  class="form-in" type="checkbox" name="editable" id="id_editable">

  </p>


  <p>
    <label class="ramochka ll" for="id_is_active">Аквтивный:</label>
    <input  class="form-in" type="checkbox" name="is_active" id="id_is_active" checked="">




  </p>
    <button class="btn btn-outline-primary my-2" type="submit">Нажать</button>
</form>
<style>
    .form-in {
        width: 300px;
        height: 35px;
        border-radius: 3px;
    }
    .ramochka {
    width: 250px;
    height: 35px;
    border-radius: 5px;
    background: white;
    border: 2px solid black;
    }
    .ll {

    padding-top: 5px;
    width: 250px;
    }
</style>
{% endblock %}